In [6]:
train_file_path = r"E:\Preparation\iNeuron\Full_Stack_Data_Science\Live_Class_Machine_Learning\ML_Project\ML_Project_Pract\Machine_Learning_Project\housing\artifact\data_ingestion\2022-07-06-17-49-29\ingested_data\train\housing.csv"

In [7]:
import pandas as pd

In [9]:
df = pd.read_csv(train_file_path)

In [11]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2237.0       706.0         2.1736             72100.0          INLAND  
1      2015.0       768.0         6.3373            279600.0      NEAR OCEAN  
2       667.0       300.0         2.8750             82700.0          INLAND  
3       898.0       483.0         2.2264            112500.0      NEAR OCEAN  
4      1837.0       580.0         4.4964            238300.0       <1H OCEAN

In [15]:
df.shape

(16512, 10)

In [21]:
X,y=df.drop(["median_house_value"],axis=1),df["median_house_value"]

In [22]:
X.shape

(16512, 9)

In [23]:
y.shape

(16512,)

In [24]:
X.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [25]:
from sklearn.impute import SimpleImputer

In [27]:
simple_inputer = SimpleImputer(strategy = "median")

In [28]:
numerical_columns = X.drop(['ocean_proximity'],axis=1)

In [29]:
numerical_columns

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  
0          2237.0       706.0         2.1736  
1          2015.0       768.0         6.3373  
2           667.0       300.0         2.8750  
3           898.0       483.0         2.2264  
4          1837.0       580.0         4.4964  
...           ...         ...            ...  
16507      2026.0      1001.0         5.0900  
16508      4769.0      1418.0         2.8139  
16509       458.0       172.0         3.1797  
16510      1208.0       501.0         4.1964  
16511       625.0       197.0         3.1319  

[16512 rows x 8 columns]

In [31]:
df_transformed = simple_inputer.fit_transform(numerical_columns)

In [32]:
df_transformed

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [38]:
simple_inputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [40]:
simple_inputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [41]:
import numpy as np

In [43]:
arr1 = np.arange(10)
arr2 = np.arange(10)

In [45]:
np.c_[arr1,arr2]

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [81]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


class FeatureGenerator(BaseEstimator, TransformerMixin):
    
    def __init__(self, add_bedrooms_per_room=True,
                 total_rooms_ix=3,
                 population_ix=5,
                 households_ix=6,
                 total_bedrooms_ix=4, columns=None):

        '''
        FeatureGenerator Initialization
        add_bedrooms_per_room: bool
        total_rooms_ix: int index number of total rooms columns
        population_ix: int index number of total population columns
        households_ix: int index number of  households columns
        total_bedrooms_ix: int index number of bedrooms columns
        '''

        try:
            self.columns = columns
            if self.columns is not None:
                total_rooms_ix = self.columns.index(total_rooms_ix)
                population_ix = self.columns.index(population_ix)
                households_ix = self.columns.index(households_ix)
                total_bedrooms_ix = self.columns.index(households_ix)

            self.add_bedrooms_per_room = add_bedrooms_per_room
            self.total_rooms_ix = total_rooms_ix
            self.population_ix = population_ix
            self.households_ix = households_ix
            self.total_bedrooms_ix = total_bedrooms_ix
        except Exception as e:
            raise HousingException(e, sys) from e

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        try:
            room_per_household = X[:, self.total_rooms_ix] / \
                                 X[:, self.households_ix]
            population_per_household = X[:, self.population_ix] / \
                                       X[:, self.households_ix]
            if self.add_bedrooms_per_room:
                bedrooms_per_room = X[:, self.total_bedrooms_ix] / \
                                    X[:, self.total_rooms_ix]
                generated_feature = np.c_[
                    X, room_per_household, population_per_household, bedrooms_per_room]
            else:
                generated_feature = np.c_[
                    X, room_per_household, population_per_household]

            return generated_feature
        except Exception as e:
            raise HousingException(e, sys) from e

In [82]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [94]:
num_pipeline = Pipeline(steps=[('imputer',SimpleImputer(strategy="median")),
('feature_generator',FeatureGenerator()),
('scaler',StandardScaler())
])

In [95]:
cat_pipeline = Pipeline(steps=[('imputer',SimpleImputer(strategy="most_frequent")),
('oneHotEncoder',OneHotEncoder()),
('scaling',StandardScaler(with_mean=False))
])

In [96]:
num_column = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income']

cat_columns = ['ocean_proximity']

preprocessing = ColumnTransformer([('num_pipeline',num_pipeline,num_column),
('cat_pipeline',cat_pipeline,cat_columns)])

In [98]:
preprocessing.fit_transform(df)

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  2.9869105 ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]])

In [99]:
test_file_path = r"E:\Preparation\iNeuron\Full_Stack_Data_Science\Live_Class_Machine_Learning\ML_Project\ML_Project_Pract\Machine_Learning_Project\housing\artifact\data_ingestion\2022-07-06-17-49-29\ingested_data\test\housing.csv"

In [100]:
test_df = pd.read_csv(test_file_path)

In [101]:
preprocessing.transform(test_df)

array([[ 0.59229422, -0.71065803,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42180959, -0.35049119, -0.37006852, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56232071, -0.64985064,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.07211862, -0.56097831,  1.14093342, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.83208232, -0.93985512,  0.10708999, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.50736927, -0.67791559,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ]])

In [102]:
import dill

In [103]:
with open("preprocessing.pkl","wb") as preprocfile:
    dill.dump(preprocessing,preprocfile)

In [108]:
with open("preprocessing.pkl","rb") as preprocfile:
    preprocfileobj = dill.load(preprocfile)

In [109]:
preprocfileobj.transform(test_df)

array([[ 0.59229422, -0.71065803,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42180959, -0.35049119, -0.37006852, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56232071, -0.64985064,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.07211862, -0.56097831,  1.14093342, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.83208232, -0.93985512,  0.10708999, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.50736927, -0.67791559,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ]])